# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97eaed23f0d883a77ac50068f66c0a2d5de52cee12b3a3a405a946479d0ea410e36ebab7b26621feb23f7edc362b67522594444d53206e24b2ed006b033810c3

test:
  secret_key_base: c7e04ec801459731e170333e3920fb0c55f880077f3715e9ee9221ee8c69f67ddae42ae7991bf3fd89d9cb4c46948912efdb69b07cbe729a9da1c0c545b19b93

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
